name: Build
on:
  push:
  pull_request:
jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Configure git
        env:
           TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - name: "Install dependencies"
        run: sudo apt-get update && sudo apt-get install build-essential cmake qt5-default libprotobuf-dev protobuf-compiler libprotoc-dev protobuf-compiler-grpc libgrpc++-dev libgrpc-dev libqt5serialport5-dev google-mock libgmock-dev libgtest-dev libspdlog-dev libfmt-dev && sudo apt-get upgrade
      - name: "Install Google Test library"
        run: cd /usr/src/googletest/googletest/ && sudo cmake CMakeLists.txt && sudo make && cd lib && sudo cp *.a /usr/lib
      - name: "Install Google Mock library"
        run: cd /usr/src/googletest/googlemock/ && sudo cmake CMakeLists.txt && sudo make && cd lib && sudo cp *.a /usr/lib
      - name: "Update ldconfig"
        run: sudo ldconfig
      - name: "Install Armorial library"
        run: git clone https://github.com/MaracatronicsRobotics/Armorial.git && cd Armorial && git submodule init && git submodule update && sudo sh install.sh && cd ..
      - name: "Build Armorial-Suassuna"
        run: mkdir build && cd build && qmake .. && make -j8
